language: cpp
compiler: clang
sudo: true
branches:
  only: ci

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq -y update; fi
  - if [ $TRAVIS_OS_NAME = osx]; then brew update; fi

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sh build_scripts/linux_build; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then sh build_scripts/osx_build; fi

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ls
  - mv run_tests ../test/ && cd ../test/ && ./run_tests && cd ../build/

after_success:
  - ls
  - mkdir artifacts && mkdir ./artifacts/include && mkdir ./artifacts/lib
  - mv *.h ./artifacts/include/
  - if [ $TRAVIS_OS_NAME = linux ]; then mv *.a ./artifacts/lib/ && mv *.so ./artifacts/lib/; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then mv *.a ./artifacts/lib/ && *.dylib ./artifacts/lib/; fi

after_script:
  - ls
  - git clone $DOCS_REPO
